### ISSUE TITLE
Stop movement at specified position

### ISSUE THREAD

**Issue by grenej** [beele/HomebridgeSomfyRemote#2]
Hello, 
is there a chance to implement in the app a movement stop point where the blinds will stop. In Homekit app when I click on blinds I see scroller moving up and down, but the blinds cannot stop at specified position. They always goes up or down to 100%. On a Somfy remote I have "My" button to stop blinds movement at specified position. Would it be possible to achieve it in the app?

thanks a lot for fantastic app.

**Comment by beele** [comment]
This would require soldering up an extra wire to the "My" button and hooking this up to the pi and extending the program to support this.

For now this is not supported, only fully open or fully closed.

**Comment by grenej** [comment]
Hi. Do you plan to add My button support

**Comment by beele** [comment]
Not in the short term.
