### ISSUE TITLE
Increased duration of activation signal

### ISSUE THREAD

**Issue by ryanspire** [beele/HomebridgeSomfyRemote#3]
First of all, thank you very much for the project, it is working almost perfectly. 3 of my 4 shades open and close every tiem but the last one only works 50% of the time. If I press the button on the connected remote for a full second, the blind does respond and work properly.

Is there a way to increase the duration of the activation signal?  Is there a configuration item for that? If it is hard coded, can you help me find out which value to change to make it work for me?

Thanks for your help!
Ryan.

**Comment by beele** [comment]
Are you using multiple remotes or a single remote that controls all the shades?
If you are using multiple remotes, I've recently pushed a fix with a delay setting that can be configured on each accessory to fix this issue.

**Comment by beele** [comment]
If you update the plugin (and change the config to match the changes) the default signal duration is now 500ms instead of 100ms (and can be configured, see the readme)

**Comment by ryanspire** [comment]
@beele - Just back from a family vacation and excited to give this a try. The 500ms time should be enough to make it work more reliably for me.
I am using a single remote, that has 4 devices (2 awnings, 2 shades) configured for the same channel. This is ideal for me since all 4 devices are used to block afternoon sun. Thanks for the update and I will let you know if it works for me.

**Comment by ryanspire** [comment]
I have updated the service, updated the config and it works beautifully! Thank you very much for your work!

**Comment by beele** [comment]
Great to hear that!
