### ISSUE TITLE
How to control multiple RTS channels?

### ISSUE THREAD

**Issue by royteeuwen** [beele/HomebridgeSomfyRemote#4]
I have looked over the documentation and it looks neat! But when I check, the only thing that I see that mentions multiple channels is the "delay" setting. How do you use this to control multiple engines though? I would assume that you would also need a connector to the "My" button to be able to switch channel and then do the "click" down or up?

**Comment by royteeuwen** [comment]
And as an addendum if you read this. Did you ever try to use the Telis 1 channel and reconfigure the channel at runtime so you could use it for as many channels / engines that you want? Sounds like in theory it should be possible

**Comment by beele** [comment]
There is no support in the plugin for multiple channels at the moment.
I've programmed my Telis A remotes to control multiple shutters at once.
For each Telis remote add a new accessory block to the config with a different delay (to prevent the signal from overlapping and sometimes causing it not to work correctly)

Adding support for multiple channels could be added but I have no need for it at the moment. Feel free to add it though. An extra wire would need to be soldered to the change channel button and it would need to be incorporated in the plugin, by keeping state and possible adding buttons for each state.
