### ISSUE TITLE
Reboot loop after installation

### ISSUE THREAD

**Issue by chrismuc70** [beele/HomebridgeSomfyRemote#5]
Hey there,
after installation of the plugin and editing the config.json file homebridge cannot boot. it's in a reboot loop. journal says:
Oct 26 19:11:31 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=143/n/a
Oct 26 19:11:31 raspberrypi systemd[1]: homebridge.service: Unit entered failed state.
Oct 26 19:11:31 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.
Oct 26 19:11:39 raspberrypi systemd[1]: Stopped Node.js HomeKit Server.
Oct 26 19:12:23 raspberrypi systemd[1]: Started Node.js HomeKit Server.

Any ideas what might be wrong?
Thanks.

**Comment by beele** [comment]
Is your config.json valid?

**Comment by chrismuc70** [comment]
yes.
found another error message in the log:
bcm2835 init: Unable to open /dev/gpiomem: Permission denied

**Comment by beele** [comment]
Looks like there is a problem with access to the gpio. Can you try controlling one of the pins manually without using homebridge?

**Comment by chrismuc70** [comment]
i am not really familiar with this... newbie here ;)

**Comment by beele** [comment]
What raspberry pi are you running this on? What operating system are you running on it?

**Comment by chrismuc70** [comment]
Raspberry Pi 3 Model B Plus Rev 1.3
Raspbian GNU/Linux 9 (stretch)

**Comment by beele** [comment]
Try this:

Enable /dev/gpiomem access
By default the module will use /dev/gpiomem when using simple GPIO access. To access this device, your user will need to be a member of the gpio group, and you may need to configure udev with the following rule (as root):

$ cat >/etc/udev/rules.d/20-gpiomem.rules <<EOF
SUBSYSTEM=="bcm2835-gpiomem", KERNEL=="gpiomem", GROUP="gpio", MODE="0660"
EOF

**Comment by chrismuc70** [comment]
tried it, but that's what it says:

-bash: /etc/udev/rules.d/20-gpiomem.rules: Permission denied

**Comment by beele** [comment]
Looks like something is messed up with your pi installation then.

**Comment by chrismuc70** [comment]
Right. Tried a lot of things. But a complete reinstall fixed it. Plugin is now working.
Closing this thread now.
Thanks.
